---
apiVersion: "logging.openshift.io/v1alpha1"
kind: "Elasticsearch"
metadata:
  name: "elasticsearch"
spec:
  nodeSpec:
    image: 172.30.1.1:5000/openshift/logging-elasticsearch5:latest
  nodes:
    - roles:
      - client
      - data
      - master
      replicas: 1
      resources:
        limits:
          memory: 1Gi
        requests:
          memory: 512Mi
