apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: elasticsearch-template
parameters:
- name: NAMESPACE
  value: elasticsearch
- name: ELASTICSEARCH_ADMIN_USER
  value: developer
objects:
- apiVersion: apiextensions.k8s.io/v1beta1
  kind: CustomResourceDefinition
  metadata:
    name: elasticsearchs.elasticsearch.redhat.com
  spec:
    group: elasticsearch.redhat.com
    names:
      kind: Elasticsearch
      listKind: ElasticsearchList
      plural: elasticsearchs
      singular: elasticsearch
    scope: Namespaced
    version: v1alpha1
- kind: Role
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: elasticsearch-operator
    namespace: ${NAMESPACE}
  rules:
  - apiGroups:
    - elasticsearch.redhat.com
    resources:
    - "*"
    verbs:
    - "*"
  - apiGroups:
    - ""
    resources:
    - pods
    - services
    - endpoints
    - persistentvolumeclaims
    - events
    - configmaps
    - secrets
    verbs:
    - "*"
  - apiGroups:
    - apps
    resources:
    - deployments
    - daemonsets
    - replicasets
    - statefulsets
    verbs:
    - "*"
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: default-account-elasticsearch-operator
    namespace: ${NAMESPACE}
  subjects:
  - kind: ServiceAccount
    name: default
  roleRef:
    kind: Role
    name: elasticsearch-operator
    apiGroup: rbac.authorization.k8s.io
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1beta1
  metadata:
    name: user-elasticsearch-operator
    namespace: ${NAMESPACE}
  subjects:
  - kind: User
    name: ${ELASTICSEARCH_ADMIN_USER}
  roleRef:
    kind: Role
    name: elasticsearch-operator
    apiGroup: rbac.authorization.k8s.io
